env:
    browser: true
overrides:
    - files:
        - "*.ts"
      env:
        es6: true
      extends:
        - plugin:vue/essential
        - eslint:recommended
        - "@vue/typescript/recommended"
        - "@vue/prettier"
        - "@vue/prettier/@typescript-eslint"
      parserOptions:
        ecmaVersion: 2018
        project: tsconfig.json
        sourceType: module
      rules:
        "@typescript-eslint/no-unused-vars":
          - error
          - args: all
            argsIgnorePattern: ^_
        prettier/prettier:
          - warn
          - arrowParens: avoid
            bracketSpacing: true
            endOfLine: auto
            semi: true
            singleQuote: true
            trailingComma: none
            useTabs: true
